import type { MetadataRoute } from "next";

// PWA manifest — lets mobile users "Add to Home Screen" and improves
// install/share signals. Icons are generated by app/icon.tsx & apple-icon.tsx.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "CareerIntel SA — AI Career Intelligence",
    short_name: "CareerIntel SA",
    description:
      "South Africa's AI-powered career intelligence platform. CVs, salary benchmarks, skills gap analysis and career coaching.",
    start_url: "/",
    display: "standalone",
    background_color: "#050B1A",
    theme_color: "#050B1A",
    lang: "en-ZA",
    categories: ["education", "productivity", "business"],
    icons: [
      { src: "/icon", sizes: "64x64", type: "image/png" },
      { src: "/apple-icon", sizes: "180x180", type: "image/png" },
    ],
  };
}
