"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { Search, Bookmark, Check, X } from "lucide-react";
import { WEAVE_CAREERS, WEAVE_SECTORS, type WeaveCareer } from "@/lib/data/weave-index.generated";
import { formatZar, confidenceLabel, SALARY_SOURCES } from "@/lib/data/salary-model";
import { useJourney } from "@/hooks/use-journey";
import { JourneyHeader, JourneyFooter } from "./chrome";
export function JourneyExplorer() {
  const [query, setQuery] = useState(""); const [sector, setSector] = useState(""); const [limit, setLimit] = useState(18);
  const [comparison, setComparison] = useState<string[]>([]); const [shortlistOnly, setShortlistOnly] = useState(false);
  const { journey, busy, error, save, loading, isSignedIn, load } = useJourney();
  const filtered = useMemo(() => WEAVE_CAREERS.filter(c => (!sector || c.sector === sector) && (!shortlistOnly || journey.shortlist.includes(c.id)) && `${c.title} ${c.sector} ${c.topSkills.join(" ")}`.toLowerCase().includes(query.trim().toLowerCase())).sort((a,b) => a.title.localeCompare(b.title)), [query, sector, shortlistOnly, journey.shortlist]);
  const compared = comparison.map(id => WEAVE_CAREERS.find(c => c.id === id)!).filter(Boolean);
  const row = (label: string, render: (c: WeaveCareer) => React.ReactNode) => <tr><th scope="row">{label}</th>{compared.map(c => <td key={c.id}>{render(c)}</td>)}</tr>;
  return <div className="journey-surface"><JourneyHeader /><main id="main-content" className="journey-container journey-section"><p className="journey-eyebrow">Explore possibilities · {WEAVE_CAREERS.length} careers</p><h1 className="journey-title">Get curious about<br /><em>where you could go.</em></h1><p className="journey-lead">Start with a career, a skill or an interest. Compare possibilities and save the ones you want to explore further.</p><div className="journey-explorer-controls"><label className="journey-search"><Search size={19} /><span className="sr-only">Search careers or skills</span><input value={query} placeholder="Try teaching, electrician or Excel…" onChange={e => { setQuery(e.target.value); setLimit(18); }} /></label><label><span className="sr-only">Filter by sector</span><select value={sector} onChange={e => { setSector(e.target.value); setLimit(18); }}><option value="">All sectors</option>{WEAVE_SECTORS.map(s => <option key={s}>{s}</option>)}</select></label>{isSignedIn && <button className="journey-button secondary" aria-pressed={shortlistOnly} onClick={() => { setShortlistOnly(!shortlistOnly); setLimit(18); }}><Bookmark size={17} />{shortlistOnly ? "Show all careers" : "My shortlist"}</button>}</div>
  {error && <div className="journey-error" role="alert">{error}<button onClick={() => void load()} className="journey-text-link">Reload saved careers</button></div>}
  <p className="journey-caption" role="status">{filtered.length} careers found · Select up to 3 to compare · {busy ? "Saving…" : "Indicative information, not a promise of employment or pay."}</p>
  {compared.length > 0 && <section className="journey-card my-6" aria-label="Career comparison"><div className="journey-section-heading"><h2>Compare your possibilities</h2><button className="journey-text-link" onClick={() => setComparison([])}>Clear comparison <X size={16} /></button></div><div className="journey-table-scroll"><table className="journey-table"><caption className="sr-only">Comparison of selected careers</caption><thead><tr><th scope="col">What matters</th>{compared.map(c => <th scope="col" key={c.id}>{c.title}<button className="journey-text-link" aria-label={`Remove ${c.title} from comparison`} onClick={() => setComparison(comparison.filter(id => id !== c.id))}><X size={16} /></button></th>)}</tr></thead><tbody>{row("Sector", c => c.sector)}{row("Indicative monthly pay", c => `${formatZar(c.minSalaryZar)}–${formatZar(c.maxSalaryZar)}`)}{row("Salary basis", c => confidenceLabel(c.dataConfidence))}{row("Skills to explore", c => c.topSkills.join(", "))}{row("Indicative NQF level", c => c.nqfLevel ? `Level ${c.nqfLevel} — check the specific route` : "Check employer or provider requirements")}{row("Remote possibilities", c => c.remoteFriendly ? "Possible in some roles" : "Usually on site")}{row("Next step", c => <Link className="journey-text-link" href={`/explore/${c.id}`}>Explore requirements →</Link>)}</tbody></table></div></section>}
  <div className="journey-grid three">{filtered.slice(0, limit).map(c => { const selected = comparison.includes(c.id); const saved = journey.shortlist.includes(c.id); return <article className="journey-card career-card" key={c.id}><p className="journey-eyebrow">{c.sector}</p><h2><Link href={`/explore/${c.id}`}>{c.title}</Link></h2><p>{c.topSkills.slice(0, 3).join(" · ")}</p><div className="journey-career-pay"><strong>{formatZar(c.minSalaryZar)}–{formatZar(c.maxSalaryZar)}</strong><span>Indicative monthly range · {confidenceLabel(c.dataConfidence)}</span></div><Link className="journey-text-link" href={`/explore/${c.id}`}>Explore this career →</Link><div className="journey-career-actions"><button aria-pressed={selected} disabled={!selected && comparison.length >= 3} className="journey-button secondary" onClick={() => setComparison(selected ? comparison.filter(id => id !== c.id) : [...comparison, c.id])}>{selected && <Check size={15} />}Compare</button>{isSignedIn ? <button aria-label={`${saved ? "Remove" : "Save"} ${c.title}`} aria-pressed={saved} disabled={busy || loading || !!error} className="journey-button secondary" onClick={() => void save({ type: "shortlist", careerId: c.id, saved: !saved, version: journey.version })}><Bookmark size={16} fill={saved ? "currentColor" : "none"} />{saved ? "Saved" : "Save"}</button> : <Link className="journey-button secondary" href={`/dashboard?career=${c.id}`} onClick={() => { try { sessionStorage.setItem("ci-pending-career", c.id); } catch {} }}>Sign in to save</Link>}</div></article>; })}</div>
  {filtered.length === 0 && <div className="journey-card"><h2>{shortlistOnly ? "Your shortlist is waiting for possibilities." : "No careers match this search."}</h2><p>Try another skill or a broader career name.</p><button className="journey-button secondary" onClick={() => { setQuery(""); setSector(""); setShortlistOnly(false); }}>Show all careers</button></div>}{filtered.length > limit && <button className="journey-button secondary mt-7" onClick={() => setLimit(limit + 18)}>Show more careers ({filtered.length - limit} remaining)</button>}
  <details className="journey-card mt-8"><summary>Where does this information come from?</summary><p>The catalogue was last refreshed in August 2026. Salary ranges combine survey information, estimates and wage-floor modelling. They are not live vacancies or guaranteed starting salaries. A gazetted basis does not mean an entire salary range is set by law.</p><p>Catalogue references: {SALARY_SOURCES}.</p><p>Entry requirements vary by employer and institution. NQF levels are indicative; check the qualification, professional registration and practical experience required for your chosen route.</p><Link href="/career-map" className="journey-text-link">Explore the interactive career map →</Link></details></main><JourneyFooter /></div>;
}
