"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import type { MarketMetric } from "@/lib/market-source";
type Source={scheduledRefreshConfigured:boolean;key:string;payload:MarketMetric[]|null;checkedAt:string|null;error:string|null};
export function MarketSignals(){
 const [sources,setSources]=useState<Source[]>([]),[error,setError]=useState(false);
 useEffect(()=>{let active=true;async function check(){try{const r=await fetch("/api/data-status");if(!r.ok)throw new Error();const data=await r.json();if(active){setSources(data);setError(false)}}catch{if(active)setError(true)}}void check();const timer=setInterval(check,300000);return()=>{active=false;clearInterval(timer)}},[]);
 return <section className="market-signals" aria-label="Source-backed market signals"><div className="journey-grid two">{sources.map(s=><article className="journey-card" key={s.key}><p className="journey-eyebrow">{s.key==="adzuna"?"Job advertising activity":"Annual labour market context"}</p>{s.payload?.map(m=><div key={m.label}><h3>{m.label}</h3><p className="market-value">{s.key==="world-bank"?`${m.value.toFixed(1)}%`:m.value.toLocaleString("en-ZA")}</p><p>{m.period} · <a href={m.url} target="_blank" rel="noreferrer">{m.source}</a></p></div>)}{!s.payload&&<p>No verified observation available yet.</p>}<p className="journey-caption">{s.checkedAt?`Last successful check: ${new Date(s.checkedAt).toLocaleString("en-ZA")}`:"Awaiting first successful check"}</p>{s.error&&<p role="status">{s.error}</p>}</article>)}</div>{!sources.length&&<p role="status">{error?"Market data is temporarily unavailable. Please try again later.":"Checking market sources…"}</p>}{sources.length>0&&error&&<p role="status">The latest check failed. Displaying the last loaded observations.</p>}{sources.some(s=>!s.scheduledRefreshConfigured)&&<p role="status">Scheduled refresh is awaiting server configuration. Visits still trigger source checks.</p>}<p className="journey-caption">Annual estimates are not quarterly Stats SA figures. Adverts are not a count of all vacancies. Career rankings and salary ranges are curated guidance. <Link href="/data-sources">Sources & update policy →</Link></p></section>
}