/**
 * Generates `lib/data/career-index.generated.ts` — the slim career index the
 * landing-page Probe hero ships to the browser.
 *
 * Why this exists: `lib/data/sa-careers.ts` is ~215KB of source. Importing it
 * into a client component pulls every field of every row into the landing-page
 * bundle — demand scores, automation risk, NQF levels, related careers — none of
 * which the hero uses. Object fields cannot be tree-shaken, so the only way to
 * pay for what we use is to emit a narrower array.
 *
 * Runs as part of `npm run build`, so the index can never drift from the source
 * data. The generated file is committed so `next dev` works without running it.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { SA_CAREERS } from "../lib/data/sa-careers";

const OUT = join(process.cwd(), "lib", "data", "career-index.generated.ts");
const WEAVE_OUT = join(process.cwd(), "lib", "data", "weave-index.generated.ts");

/**
 * `topSkills` is deliberately excluded. Carrying four skills per row costs
 * 23KB raw / 8KB gzipped and buys skill-term search ("python" -> Data
 * Scientist) — which people use on /job-market, where the full dataset is
 * already loaded, but not in a hero where they type their own job title.
 * The plain-English gap is covered by SEARCH_ALIASES instead, which is
 * a fraction of the size.
 */
/**
 * Field names match `lib/data/sa-careers.ts` exactly rather than being shortened.
 * Short keys looked like a saving but measured at 0.1KB gzipped across all 307
 * rows — gzip collapses repeated keys — while costing structural compatibility
 * with the shared salary model. Keeping the canonical names means ProbeCareer
 * satisfies SalaryInput directly, with no adapter and no per-render allocation.
 */
const rows = SA_CAREERS.map((c) => ({
  id: c.id,
  title: c.title,
  sector: c.sector,
  minSalaryZar: c.minSalaryZar,
  avgSalaryZar: c.avgSalaryZar,
  maxSalaryZar: c.maxSalaryZar,
  topProvinces: c.topProvinces,
  ...(c.dataConfidence ? { dataConfidence: c.dataConfidence } : {}),
}));

const body = `// AUTO-GENERATED by scripts/build-career-index.ts — do not edit by hand.
// Regenerate with: npx tsx scripts/build-career-index.ts
// Source of truth: lib/data/sa-careers.ts

/**
 * The narrow slice of a career the Probe hero needs. Field names match
 * CareerDemandData, so this satisfies SalaryInput in lib/data/salary-model.ts.
 */
export interface ProbeCareer {
  id: string;
  title: string;
  sector: string;
  /** Published monthly ZAR range, before province and experience adjustment. */
  minSalaryZar: number;
  avgSalaryZar: number;
  maxSalaryZar: number;
  /** Province codes that actually hire for this role. */
  topProvinces: string[];
  dataConfidence?: "gazetted" | "surveyed" | "estimated";
}

export const CAREER_INDEX: ProbeCareer[] = ${JSON.stringify(rows, null, 0)};

export const CAREER_INDEX_COUNT = ${rows.length};
`;

writeFileSync(OUT, body, "utf8");

const kb = (n: number) => (n / 1024).toFixed(1) + "KB";
console.log(
  `career-index: ${rows.length} careers -> ${OUT.replace(process.cwd(), ".")} (${kb(body.length)}, data ${kb(JSON.stringify(rows).length)})`
);

// ─────────────────────────────────────────────────────────────────────────────
// Weave index — the /explore career map.
//
// Richer than the Probe index because the map encodes four dimensions at once
// (position, size, colour, links) and the detail panel reads skills and NQF.
// Still narrower than SA_CAREERS: growth trend, future outlook and the long
// prose fields are left out.
//
// `related` is resolved from relatedCareers TITLES to ids here, at build time,
// so the browser never ships the title strings just to match them up.
// ─────────────────────────────────────────────────────────────────────────────
const byTitle = new Map(SA_CAREERS.map((c) => [c.title.toLowerCase(), c.id]));

const weaveRows = SA_CAREERS.map((c) => ({
  id: c.id,
  title: c.title,
  sector: c.sector,
  demandScore: c.demandScore,
  automationRisk: c.automationRisk,
  avgSalaryZar: c.avgSalaryZar,
  minSalaryZar: c.minSalaryZar,
  maxSalaryZar: c.maxSalaryZar,
  nqfLevel: c.nqfLevel ?? null,
  remoteFriendly: c.remoteFriendly,
  internationalDemand: c.internationalDemand,
  topSkills: c.topSkills.slice(0, 6),
  topProvinces: c.topProvinces,
  related: (c.relatedCareers ?? [])
    .map((t) => byTitle.get(t.toLowerCase()))
    .filter((id): id is string => Boolean(id) && id !== c.id),
  ...(c.dataConfidence ? { dataConfidence: c.dataConfidence } : {}),
}));

const weaveBody = `// AUTO-GENERATED by scripts/build-career-index.ts — do not edit by hand.
// Regenerate with: npx tsx scripts/build-career-index.ts
// Source of truth: lib/data/sa-careers.ts

/** A career as the /explore weave draws and describes it. */
export interface WeaveCareer {
  id: string;
  title: string;
  sector: string;
  demandScore: number;
  automationRisk: number;
  avgSalaryZar: number;
  minSalaryZar: number;
  maxSalaryZar: number;
  nqfLevel: number | null;
  remoteFriendly: boolean;
  internationalDemand: boolean;
  topSkills: string[];
  topProvinces: string[];
  /** Ids of related careers, resolved from titles at build time. */
  related: string[];
  dataConfidence?: "gazetted" | "surveyed" | "estimated";
}

export const WEAVE_CAREERS: WeaveCareer[] = ${JSON.stringify(weaveRows, null, 0)};

export const WEAVE_SECTORS: string[] = ${JSON.stringify(
  [...new Set(SA_CAREERS.map((c) => c.sector))].sort(),
  null,
  0
)};

/**
 * Both scales are normalised against the range the data actually occupies.
 * demandScore never drops below the low 60s and automationRisk never exceeds
 * the mid 50s, so scoring either against a nominal 0-100 collapses every career
 * into one ring of one colour and the encoding carries no information.
 */
export const WEAVE_RANGES = {
  demand: { min: ${Math.min(...SA_CAREERS.map((c) => c.demandScore))}, max: ${Math.max(...SA_CAREERS.map((c) => c.demandScore))} },
  automation: { min: ${Math.min(...SA_CAREERS.map((c) => c.automationRisk))}, max: ${Math.max(...SA_CAREERS.map((c) => c.automationRisk))} },
  salary: { min: ${Math.min(...SA_CAREERS.map((c) => c.avgSalaryZar))}, max: ${Math.max(...SA_CAREERS.map((c) => c.avgSalaryZar))} },
} as const;
`;

writeFileSync(WEAVE_OUT, weaveBody, "utf8");
console.log(
  `weave-index:  ${weaveRows.length} careers, ${
    weaveRows.reduce((n, r) => n + r.related.length, 0)
  } links -> ${WEAVE_OUT.replace(process.cwd(), ".")} (${kb(weaveBody.length)})`
);
