/**
 * Generates `lib/data/career-index.generated.ts` — the slim career index the
 * landing-page Probe hero ships to the browser.
 *
 * Why this exists: `lib/data/sa-careers.ts` is ~215KB of source. Importing it
 * into a client component pulls every field of every row into the landing-page
 * bundle — demand scores, automation risk, NQF levels, related careers — none of
 * which the hero uses. Object fields cannot be tree-shaken, so the only way to
 * pay for what we use is to emit a narrower array.
 *
 * Runs as part of `npm run build`, so the index can never drift from the source
 * data. The generated file is committed so `next dev` works without running it.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { SA_CAREERS } from "../lib/data/sa-careers";

const OUT = join(process.cwd(), "lib", "data", "career-index.generated.ts");

/**
 * `topSkills` is deliberately excluded. Carrying four skills per row costs
 * 23KB raw / 8KB gzipped and buys skill-term search ("python" -> Data
 * Scientist) — which people use on /job-market, where the full dataset is
 * already loaded, but not in a hero where they type their own job title.
 * The plain-English gap is covered by SEARCH_ALIASES instead, which is
 * a fraction of the size.
 */
/**
 * Field names match `lib/data/sa-careers.ts` exactly rather than being shortened.
 * Short keys looked like a saving but measured at 0.1KB gzipped across all 307
 * rows — gzip collapses repeated keys — while costing structural compatibility
 * with the shared salary model. Keeping the canonical names means ProbeCareer
 * satisfies SalaryInput directly, with no adapter and no per-render allocation.
 */
const rows = SA_CAREERS.map((c) => ({
  id: c.id,
  title: c.title,
  sector: c.sector,
  minSalaryZar: c.minSalaryZar,
  avgSalaryZar: c.avgSalaryZar,
  maxSalaryZar: c.maxSalaryZar,
  topProvinces: c.topProvinces,
  ...(c.dataConfidence ? { dataConfidence: c.dataConfidence } : {}),
}));

const body = `// AUTO-GENERATED by scripts/build-career-index.ts — do not edit by hand.
// Regenerate with: npx tsx scripts/build-career-index.ts
// Source of truth: lib/data/sa-careers.ts

/**
 * The narrow slice of a career the Probe hero needs. Field names match
 * CareerDemandData, so this satisfies SalaryInput in lib/data/salary-model.ts.
 */
export interface ProbeCareer {
  id: string;
  title: string;
  sector: string;
  /** Published monthly ZAR range, before province and experience adjustment. */
  minSalaryZar: number;
  avgSalaryZar: number;
  maxSalaryZar: number;
  /** Province codes that actually hire for this role. */
  topProvinces: string[];
  dataConfidence?: "gazetted" | "surveyed" | "estimated";
}

export const CAREER_INDEX: ProbeCareer[] = ${JSON.stringify(rows, null, 0)};

export const CAREER_INDEX_COUNT = ${rows.length};
`;

writeFileSync(OUT, body, "utf8");

const kb = (n: number) => (n / 1024).toFixed(1) + "KB";
console.log(
  `career-index: ${rows.length} careers -> ${OUT.replace(process.cwd(), ".")} (${kb(body.length)}, data ${kb(JSON.stringify(rows).length)})`
);
